name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Unit Tests
        run: mvn compile test verify
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: surefire-reports/junit-reports/*.xml
      - name: Sonarqube Scan
        run: mvn verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -DskipTests --settings settings.xml
        env:
          MAVEN_DANODIC_DEV_USERNAME: ${{ secrets.PACKAGES_USERNAME }}
          MAVEN_DANODIC_DEV_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: jao-java ${{ github.ref }}
          body_path: RELEASE.md
          draft: false
          prerelease: false
